# Generated by Django 5.0.3 on 2024-03-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtask',
            name='date',
            field=models.DateField(),
        ),
    ]
